### ISSUE TITLE
Webserver not really needed. And an Arch PKGBUILD

### ISSUE THREAD

**Issue by gripped** [LeonardLaszlo/popcorn-time-building-guide-armv7#1]
Hi 
Thanks for the work you have done on this.
I just made an Arch PKGBUILD and package for my XU3. Quick test and It worked.
https://github.com/gripped/odroid-xu3-pkgbuilds/tree/master/popcorntime-xu3

Setting up a webserver to download nwjs-v0.12.0-linux-arm.tar.gz is not feasible in the scope of a PKGBUILD so I just hardcoded the address of the file on this github
`        if (plattform.type === 'linuxarm') {
		plattform.url = "https://raw.githubusercontent.com/LeonardLaszlo/popcorn-time-building-guide-armv7/master/nwjs-v0.12.0-linux-arm.tar.gz";`

Again thanks

**Comment by LeonardLaszlo** [comment]
Cool! Please commit this change to my repo!
